### ISSUE TITLE
castException for same class 

### ISSUE THREAD

**Issue by ToniYang** [twitter/chill#254]
I want to send object to another application with kryo,but I can not cast same class in another jvm.
`val instantiator = new ScalaKryoInstantiator
    instantiator.setRegistrationRequired(false)
    val kryo = instantiator.newKryo()
    val baos = new ByteArrayOutputStream
    val output = new Output(baos,4096)
    kryo.readObject(new Input(output.toBytes), SingleCrawlRecord.getClass)`
I got an exception said can't cast class SingleCrawlRecord to SingleCrawlRecord, I searched for the question, It's because the defferent classsloader,can chill support this?

**Comment by ToniYang** [comment]
`val instantiator = new ScalaKryoInstantiator

```
instantiator.setRegistrationRequired(false)
val kryo = instantiator.newKryo()

val b4 = System.currentTimeMillis()
val baos = new ByteArrayOutputStream
val output = new Output(baos,4096)
kryo.writeObject(output,a)

kryo.setReferences(false)
kryo.readObject(new Input(output.toBytes), SingleCrawlRecord.getClass).asInstanceOf[SingleCrawlRecord]
print(System.currentTimeMillis() - b4)`
```

`Exception in thread "main" java.lang.ClassCastException: com.crawler.policy.bean.SingleCrawlRecord$ cannot be cast to com.crawler.policy.bean.SingleCrawlRecord`

**Comment by johnynek** [comment]
See:
https://github.com/twitter/chill/blob/develop/chill-java/src/main/java/com/twitter/chill/KryoInstantiator.java

you can control the instantiator. You might want this option:
https://github.com/twitter/chill/blob/develop/chill-java/src/main/java/com/twitter/chill/KryoInstantiator.java#L88

or you might just want a new subclass of KryoInstantiator (which is just a class to make a new `Kryo` instance with the options you want. But the default is already using the current thread classloader:
https://github.com/twitter/chill/blob/develop/chill-scala/src/main/scala/com/twitter/chill/ScalaKryoInstantiator.scala#L61

I don't know your classloader situation well enough to say what the issue is (and I'm not an expert on classloaders).

**Comment by ToniYang** [comment]
I made a mistake, SingleCrawlRecord.getClass should change to classOf[SingleCrawlRecord]. The two has a small different.
